[package]
name = "vrcosc"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
rosc = "0.10.1"
strum = { version = "0.26.3", features = ["derive"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
